/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	v1alpha1 "volcano.sh/apis/pkg/apis/batch/v1alpha1"
	batchv1alpha1 "volcano.sh/apis/pkg/client/applyconfiguration/batch/v1alpha1"
	scheme "volcano.sh/apis/pkg/client/clientset/versioned/scheme"
)

// HyperJobsGetter has a method to return a HyperJobInterface.
// A group's client should implement this interface.
type HyperJobsGetter interface {
	HyperJobs(namespace string) HyperJobInterface
}

// HyperJobInterface has methods to work with HyperJob resources.
type HyperJobInterface interface {
	Create(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.CreateOptions) (*v1alpha1.HyperJob, error)
	Update(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.UpdateOptions) (*v1alpha1.HyperJob, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, hyperJob *v1alpha1.HyperJob, opts v1.UpdateOptions) (*v1alpha1.HyperJob, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.HyperJob, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.HyperJobList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.HyperJob, err error)
	Apply(ctx context.Context, hyperJob *batchv1alpha1.HyperJobApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.HyperJob, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, hyperJob *batchv1alpha1.HyperJobApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.HyperJob, err error)
	HyperJobExpansion
}

// hyperJobs implements HyperJobInterface
type hyperJobs struct {
	*gentype.ClientWithListAndApply[*v1alpha1.HyperJob, *v1alpha1.HyperJobList, *batchv1alpha1.HyperJobApplyConfiguration]
}

// newHyperJobs returns a HyperJobs
func newHyperJobs(c *BatchV1alpha1Client, namespace string) *hyperJobs {
	return &hyperJobs{
		gentype.NewClientWithListAndApply[*v1alpha1.HyperJob, *v1alpha1.HyperJobList, *batchv1alpha1.HyperJobApplyConfiguration](
			"hyperjobs",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *v1alpha1.HyperJob { return &v1alpha1.HyperJob{} },
			func() *v1alpha1.HyperJobList { return &v1alpha1.HyperJobList{} }),
	}
}
